const productlistings = [
    {
      product: "A2 Milk",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168261/organic_products/a2milk_liva1w.png" },
      price: 100,
      category: "Milk Products",
      order:1,
      suborder:1,
      quantity:"1 Litre",
      description:"A2 Milk is the real thing - it's fresh, unadulterated milk from happy cows that have been grazing in open pastures. We deliver this milk directly to your doorstep, across Bengaluru. We believe that fresh, unadulterated milk is best for your health, and we take great care to ensure that the milk is natural, fresh, and of the highest quality. We test it for quality, chill it below 4 degrees Celsius, and pack it in sanitized glass bottles to preserve its freshness",
    },
    {
      product: "A2 Ghee",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168259/organic_products/a2ghee_fis9ij.png" },
      price: 1250,
      category: "Milk Products",
      discount:1125,
      order:1,
      suborder:2,
      quantity:"500 ml",
      description:"Indulge in the unparalleled freshness of Atma Nirbar Farm, a delightful sensory journey that captivates your taste buds. Immerse yourself in the invigorating aroma and vibrant flavours of handpicked, farm-fresh ingredients. Each bite is a celebration of nature's bounty, delivering a burst of crispness and succulence. With Atma Nirbar Farm, experience a symphony of freshness that elevates every meal, making it a truly memorable culinary delight",
    },
    {
      product: "A2 Butter",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168259/organic_products/a2butter_wbfswl.png" },
      price: 900,
      category: "Milk Products",
      discount:810,
      order:1,
      suborder:3,
      quantity:"500 gm",
      description:"Experience the pure richness of Amruth Desi Cow Milk Butter. Made from 100% organic milk, the cream is thoughtfully cultured and slow-churned to perfection, resulting in butter with a delightful aroma and flavour. Free from any additives or preservatives, this butter offers a clean and natural taste. Its velvety smooth texture brings the essence of true homemade butter to your culinary creations. Indulge in the goodness of Amruth Desi Cow Milk Butter, a wholesome choice that allows you to savour the pure and authentic flavours of organic dairy.",
    },
    {
      product: "Dhoop",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1719029905/organic_products/zavslqdnz8t6fucr5hvx.png" },
      price: 90,
      category: "Gou Products",
      discount:80,
      order:2,
      suborder:1,
      quantity:"Pack of 40pcs",
      description:"Dhoop Made of Cow Dung.",
    },
    {
      product: "Goarka",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168260/organic_products/goarka_ratcpv.png" },
      price: 100,
      category: "Gou Products",
      discount:90,
      order:2,
      suborder:2,
      quantity:"200 ml",
      description:"Description	Goarka (Gomutra) is collected from pure desi cows. Desi cow Gomutra has special micro-organisms, beneficial bacterias, and minerals. It has various applications in our daily life. Desi Cow Goumutra is anti-bacterial. It can be sprinkled in the house or used as a cleaning liquid for mopping the floor. It kills bacterias and germs and keeps the environment clean and safe. In Hindu tradition, it is used in various ceremonies and sacrifices. Gomutra is rich in beneficial bacterias and micro-organisms. It used as an organic fertilizer for plants and vegetables. It helps plants to grow faster and healthier.",
    },
    {
      product: "Sambrani Cup",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1718965777/organic_products/qqivnxkj0xkmxqxou9nh.jpg" },
      price: 105,
      category: "Gou Products",
      discount:95,
      order:2,
      suborder:3,
      quantity:"Pack of 12pcs",
      description:"Discover the Atma Nirbhar Farm's Pure Desi Cow Dung Sambrani Cups. These Cups are made with Pure Desi Cow Dung along with Havan Samagri for a devotional and convinient Sambrani experience in your pooja room.By lightening the Desi Cow Dung Sambrani in your Pooja Room/ Meditation room/ Home during Sunrise and Sunset will increase pure oxygen and positive energy in the surrounding atmosphere.Our Atma Nirbhar Farm's Pure Desi Cow Dung Sambrani Cups well designed for Daily Pooja, Festivals and Rituals. The Sambrani cups come with a steel stand. Place the Sambrani cup on the steel stand by placing a camphor and ignite the Camphor to blaze the Sambrani Cup. Once the Cup started burning, place it on the steel stand.Instructions: Keep away from children when its burning.",
    },
    {
      product: "Cow Dung Cake",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168259/organic_products/cowdung_p7bazm.png" },
      price: 100,
      discount:80,
      category: "Gou Products",
      order:2,
      suborder:4,
      quantity:"Pack of 10",
      description:"Description	Our cow dung cakes are made from pure desi cows. Desi cow dung has special properties and quite useful for fire sacrifices. The mixture of cow dung and Gomutra are made into small cakes and dried under the sun for 4 to 5 days. The sun-dried cakes always burn well. Burning cow dung cake at home along with ghee purifies the air, kills airborne germs, and dispels evil effects. It keeps the environment clean. Cow dung cake is most preferred for homa, Agnihotra, etc. Dried cow dung can be broken into small pieces and added to plant as manure. Mix with soil and add water. Nutrients in cow dung will boost plant growth and improve soil health.",
    },
    {
      product: "Vermi Compost",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168268/organic_products/vermicompost_f8syj4.png" },
      price: 45,
      discount:35,
      category: "Gou Products",
      order:2,
      suborder:5,
      quantity:"1 Kg",
      description:"Description	Vermicompost by Atma Nirbar Farm, is 100% organic, farm produced with zero chemicals, and cow dung-based manure. It's a highly nutrient-rich organic fertilizer & manure for the healthy and fast growth of plants. Vermicompost is nature friendly, non-toxic & preferred nutrient source for home gardening as well as for organic farming. It's an active biological mixture of bacteria and enzymes, and rich in bio-available nutrients such as Nitrogen, Potassium & Phosphorus.",
    },
    {
      product: "Groundnut Oil",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168261/organic_products/groundnutoil_qhvzyu.png" },
      price: 390,
      discount:330,
      category: "Cp Oils",
      order:3,
      suborder:1,
      quantity:"1 Litre",
      description:"Best Quality groundnuts are used to extract groundnut oil using a traditional wood pressed method like in the olden days to urge pure and Wooden pressed groundnut oil which helps to stands out for its natural deep yellow colour and natural aroma. It’s been predominantly used as cooking oil within the southern part of India for hundreds of years.",
    },
    {
      product: "Coconut Oil",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168259/organic_products/coconutoil_qd80jc.png" },
      price: 410,
      discount:370,
      category: "Cp Oils",
      order:3,
      suborder:2,
      quantity:"1 Litre",
      description:" Best quality coconuts are used to extract coconut oil using a traditional wooden pressed method like in the olden days to induce pure and Wooden Pressed coconut oil. The wood-pressing method ensures that each nutrient and rich taste are retained. Abhayam coconut oil is full of essential nutrients and is right for your cooking, baking, oil pulling, skin, and hair care!",
      
    },
    {
      product: "Sesame Oil",
      image1: { path: "" },
      price: 510,
      discount:470,
      category: "Cp Oils",
      order:3,
      suborder:3,
      quantity:"1 Litre",
      description:"Best quality sesame are used to extract sesame oil using a traditional wooden pressed method like in the olden days to induce pure and Wooden Pressed sesame oil. The wood-pressing method ensures that each nutrient and rich taste are retained. Abhayam sesame oil is full of essential nutrients and is right for your cooking.",
    },
    {
      product: "Mustard Oil",
      image1: { path: "" },
      price: 360,
      discount:330,
      category: "Cp Oils",
      order:3,
      suborder:4,
      quantity:"1 Litre",
      description:"Best quality mustard are used to extract mustard oil using a traditional wooden pressed method like in the olden days to induce pure and Wooden Pressed mustard oil. The wood-pressing method ensures that each nutrient and rich taste are retained. Abhayam mustard oil is full of essential nutrients and is right for your cooking.",
    },
    {
      product: "Safflower Oil",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168265/organic_products/saffloweroil_fdtxtd.png" },
      price: 380,
      discount:360,
      category: "Cp Oils",
      order:3,
      suborder:5,
      quantity:"1 Litre",
      description:"Best quality Safflower are used to extract Safflower oil using a traditional wooden pressed method like in the olden days to induce pure and Wooden Pressed Safflower oil. The wood-pressing method ensures that each nutrient and rich taste are retained. Abhayam Safflower oil is full of essential nutrients and is right for your cooking",
    },
    {
      product: "Sunflower Oil",
      image1: { path: "" },
      price: 380,
      discount:340,
      category: "Cp Oils",
      order:3,
      suborder:6,
      quantity:"1 Litre",
      description:"Best quality Sunflower seeds are used to extract Sunflower oil using a traditional wooden pressed method like in the olden days to induce pure and Wooden Pressed Sunflower oil. The wood-pressing method ensures that each nutrient and rich taste are retained. Abhayam Sunflower oil is full of essential nutrients and is right for your cooking.",
    },
    {
      product: "Castor Oil",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168259/organic_products/castoroil_svhdep.png" },
      price: 380,
      category: "Cp Oils",
      order:3,
      suborder:7,
      quantity:"1 Litre",
      description:"Best quality Castor are used to extract Castor oil using a traditional wooden pressed method like in the olden days to induce pure and Wooden Pressed Castor oil. The wood-pressing method ensures that each nutrient and rich taste are retained. Abhayam Castor oil is full of essential nutrients and is right for your cooking."
    },
    {
      product: "Millet Mix",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168263/organic_products/millet_zko5tn.png" },
      price: 200,
      discount:190,
      category: "Natural & Organic Products",
      order:4,
      suborder:1,
      quantity:"500 gm",
      description:" Nityamrutha Health Mix (Millets Mix) is the perfect breakfast fix for everyone at home. The Nityamrutha Fresh Millets Health Mix keeps blood sugar levels low, helps digestion, boosts your immunity, and acts as an antioxidant. Both soluble and insoluble dietary fibre are abundant in millet. As a prebiotic the insoluble fibre in millet promotes the growth of healthy bacteria in your digestive system. Additionally, this sort of fibre is crucial for giving stool volume, which keeps you regular and lowers your risk of colon cancer. This Millet mix gives the best results when had twice a day, in the morning and at night.",
    },
    {
      product: "Millet Mix",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168263/organic_products/millet_zko5tn.png" },
      price: 380,
      discount:355,
      category: "Natural & Organic Products",
      order:4,
      suborder:2,
      quantity:"1 kg",
      description:" Nityamrutha Health Mix (Millets Mix) is the perfect breakfast fix for everyone at home. The Nityamrutha Fresh Millets Health Mix keeps blood sugar levels low, helps digestion, boosts your immunity, and acts as an antioxidant. Both soluble and insoluble dietary fibre are abundant in millet. As a prebiotic the insoluble fibre in millet promotes the growth of healthy bacteria in your digestive system. Additionally, this sort of fibre is crucial for giving stool volume, which keeps you regular and lowers your risk of colon cancer. This Millet mix gives the best results when had twice a day, in the morning and at night.",
    },
    {
      product: "Jaggery",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168265/organic_products/jaggery_khpwln.png" },
      price: 100,
      category: "Natural & Organic Products",
      order:4,
      suborder:4,
      quantity:"1 Kg",
      description:"Jaggery is made from natural sugar cane. Free from pesticides and chemical additives, Jaggery naturally contains vitamins and minerals also. It is a delicious and healthy alternative to processed sugar. Use it to enhance the taste of tea, coffee, and other beverages.",
    },
    {
      product: "Rock Salt",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168264/organic_products/rocksalt_h0ysv2.png" },
      price: 125,
      discount:105,
      category: "Natural & Organic Products",
      order:4,
      suborder:3,
      quantity:"1 Kg",
      description:"Rock salt is naturally extracted from the rocks. It is a great alternate to the normal table salt. Rich source of natural minerals like Sodium, potassium, calcium, it provides nourishment for you and enhances the flavour of food. ",
    },
    {
      product: "Rose Soap",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168265/organic_products/rosesoap_kxrn31.png" },
      price: 55,
      category: "Cosemtic Products",
      order:5,
      suborder:1,
      quantity:"1(125 gms)",
      description:"Description	Cow-Milk Rose Soap (125 Gms): Siddhagiri Soap contains Rose Water which is a great skin cleanser that aids in removing oil and dirt. It can have anti-aging properties that can help to revitalize the skin giving it a refreshing loo"
    },
    {
      product: "Panchagavya Soap",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168262/organic_products/panchagavyasoap_thgfpb.png" },
      price: 55,
      category: "Cosemtic Products",
      order:5,
      suborder:2, 
      quantity:"1(125 gms)",
      description:" Panchagavya Soap(125gms): Siddhagiri Soaps contain Panchagavya which is used to boost immunity, kill harmful bacteria and remove toxins from the Skin.",
    },
    {
      product: "Gaujal & Chandan Soap",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168259/organic_products/gaujalchandansoap_xc4yfm.png" },
      price: 55,
      category: "Cosemtic Products",
      order:5,
      suborder:3,
      quantity:"1(125 gms)",
      description:"Description	Gaujal Chandan Soap (125 Gms): Siddhagiri Soap contains Gaujal and Chandan both are time-tested ayurvedic ingredients for clear skin with anti-bacterial, anti-tanning, and anti-aging properties. Its regular use can give you baby soft skin."
    },
    {
      product: "Lime Soap",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168266/organic_products/limesoap_dfuh2t.png" },
      price: 30,
      category: "Cosemtic Products",
      order:5,
      suborder:4,
      quantity:"1(125 gms)",
      description:"Lime Soap (125 Gms): Siddhagiri Made with natural ingredients and infused with the essence of lime, this soap cleanses, refreshes, and nourishes your skin."
    },
    {
      product: "Siddadanta Toothpaste",
      image1: { path: "https://res.cloudinary.com/dyinyznt3/image/upload/v1717168267/organic_products/siddanthapaste_mconma.png" },
      price: 55,
      category: "Cosemtic Products",
      order:5,
      suborder:5,
      quantity:"1(100 gms)",
      description:"SiddhaDant Dental Cream (100gms): SiddhaDant Dental Cream is a rare combination of Ayurvedic Herbs that has extraordinary benefits to aid Oral Hygiene. Use SiddhaDant for Healthy Teeth & Refreshing Smile.",
    },
  ];
  
  module.exports = { data: productlistings };
  